import type { HeroId } from './heroes';
export type AbilityEffect = 'shock' | 'frost' | 'burst' | 'pierce' | 'bloom' | 'guard';
export interface HeroAbility { id:string; hero:HeroId; name:string; description:string; icon:string; unlockLevel:number; cooldownMs:number; juiceCost:number; damage:number; effect:AbilityEffect; }
const names:Record<HeroId,Array<[string,string,string,AbilityEffect]>>={
 jiju:[['Blue Arc','Shock the whole field for heavy damage.','⚡','shock'],['Clean Sweep','A broad balanced field strike.','✦','burst'],['Quick Draw','Pierce the nearest fruit.','➤','pierce'],['Still Frame','Freeze the field, then strike.','❄','frost'],['Orchard Guard','A steady burst that protects the wall.','⬡','guard'],['Grand Finale','A full-field finishing strike.','✹','shock']],
 topfu:[['Cold Press','Slow and crack every fruit.','❄','frost'],['Soft Crush','Burst damage around the front fruit.','●','burst'],['Brittle Wave','A freezing full-field wave.','✧','frost'],['Heavy Drop','High damage to the front pack.','⬇','pierce'],['Chill Guard','Slow the full field and steady the wall.','⬡','guard'],['Deep Freeze','Topfu’s strongest field freeze.','✹','shock']],
 lagen:[['Long Lance','Pierce a line through the field.','➤','pierce'],['Far Reach','Strike fruit across the whole field.','⌁','shock'],['Spearhead','High damage to the lead fruit.','↗','pierce'],['Raking Line','A long field-wide slash.','╱','burst'],['Vine Snare','Slow every fruit in its path.','♧','frost'],['Horizon Break','A full field lance strike.','✹','shock']],
 tripos:[['Triple Cut','Three fast cuts across the field.','≋','burst'],['Rose Burst','A powerful clustered blast.','✿','burst'],['Crosswind','Strike the field from both sides.','✣','shock'],['Pink Haze','Slow and damage every fruit.','❋','frost'],['Encore','Repeat damage on the strongest fruit.','♫','pierce'],['Grand Waltz','Tripos’ full field finale.','✹','shock']],
 ki:[['Golden Pulse','A fast full-field pulse.','☼','shock'],['Lucky Drop','A heavy burst near the lead fruit.','✦','burst'],['Sunbeam','Pierce through the leading line.','☀','pierce'],['Golden Guard','Slow fruit and protect the wall.','⬡','guard'],['Solar Bloom','Damage the entire field.','✺','burst'],['Daybreak','Ki’s strongest full-field strike.','✹','shock']],
};
export const HERO_ABILITIES:HeroAbility[]=(Object.keys(names) as HeroId[]).flatMap(hero=>names[hero].map(([name,description,icon,effect],i)=>({id:hero+'-'+(i+1),hero,name,description,icon,unlockLevel:[1,5,10,15,20,25][i]!,cooldownMs:[9000,13000,16000,19000,23000,28000][i]!,juiceCost:[0,15,20,25,30,40][i]!,damage:[18,24,30,36,44,60][i]!,effect})));
export const MAX_HERO_ABILITIES_EQUIPPED=3;
export function heroAbility(id:string):HeroAbility|undefined{return HERO_ABILITIES.find(a=>a.id===id);}
export function emptyHeroAbilityRanks():Record<string,number>{return Object.fromEntries(HERO_ABILITIES.map(a=>[a.id,0]));}
export function emptyHeroAbilityLoadouts():Record<HeroId,string[]>{return {jiju:['jiju-1'],topfu:[],lagen:[],tripos:[],ki:[]};}
export function normaliseHeroAbilityLoadouts(raw:unknown):Record<HeroId,string[]>{const base=emptyHeroAbilityLoadouts(),input=raw&&typeof raw==='object'?raw as Partial<Record<HeroId,unknown>>:{};for(const hero of Object.keys(base) as HeroId[]){const rows=Array.isArray(input[hero])?input[hero] as unknown[]:base[hero];base[hero]=[...new Set(rows.filter((id):id is string=>typeof id==='string'&&heroAbility(id)?.hero===hero))].slice(0,MAX_HERO_ABILITIES_EQUIPPED);}return base;}
