import assert from 'node:assert/strict';
import { test } from 'node:test';
import { DEFAULT_PVP_CONFIG } from './pvp';
import { DEFAULT_COOP_CONFIG, newCoopMatch, joinCoopMatch, applyCoopCommand, advanceCoopMatch, coopRewards, type CoopPlayer } from './onlineCoop';
const player=(id:string):CoopPlayer=>({userId:id,name:id,hero:'jiju',sequence:0,lastSeenAt:1000,lastSlashAt:0,kills:0});
const match=()=>{const room=newCoopMatch('test',player('one'),DEFAULT_PVP_CONFIG);joinCoopMatch(room,player('two'),1000);return room;};
test('two distinct accounts join once, countdown starts, third player cannot join',()=>{const room=match();assert.equal(room.players.length,2);assert.equal(room.status,'countdown');assert.throws(()=>joinCoopMatch(room,player('three'),1000));advanceCoopMatch(room,.2,4001,DEFAULT_PVP_CONFIG,DEFAULT_COOP_CONFIG);assert.equal(room.status,'playing');assert.equal(room.fruits.length,1);});
test('both players slice the same authoritative fruit and receive equal reward totals',()=>{const room=match();room.status='playing';room.remainingSpawns=1;room.fruits=[{id:'fruit',type:'normal',x:5,y:5,hp:60,boss:false}];const cmd={type:'slash' as const,from:{x:4,y:5},to:{x:6,y:5}};applyCoopCommand(room,'one',1,cmd,2000,DEFAULT_PVP_CONFIG);assert.equal(room.fruits[0]!.hp,25);applyCoopCommand(room,'two',1,cmd,2001,DEFAULT_PVP_CONFIG);assert.equal(room.fruits.length,0);assert.equal(room.kills,1);assert.equal(room.players[1]!.kills,1);assert.equal(room.players[0]!.lastStroke?.at,2000);room.completedWaves=6;const a=coopRewards(room,DEFAULT_COOP_CONFIG);assert.deepEqual(a,coopRewards(room,DEFAULT_COOP_CONFIG));assert.equal(a.gems,1);assert.equal(a.coins,61);});
test('shared builds debit once and reject occupied pads, replays and unauthorized actions',()=>{const room=match();room.status='playing';const before=room.fruts;applyCoopCommand(room,'one',1,{type:'build',tower:'guillotine',cell:121},2000,DEFAULT_PVP_CONFIG);assert.equal(room.fruts,before-DEFAULT_PVP_CONFIG.towers.guillotine!.cost);assert.throws(()=>applyCoopCommand(room,'two',1,{type:'build',tower:'guillotine',cell:121},2000,DEFAULT_PVP_CONFIG));assert.throws(()=>applyCoopCommand(room,'one',1,{type:'build',tower:'guillotine',cell:122},2000,DEFAULT_PVP_CONFIG));assert.throws(()=>applyCoopCommand(room,'outsider',1,{type:'leave'},2000,DEFAULT_PVP_CONFIG));assert.equal(room.towers.length,1);});
test('boss introduction counts down and creates an actual high-health boss',()=>{const room=match();room.wave=7;room.status='boss-intro';room.phaseUntil=5000;advanceCoopMatch(room,.2,4900,DEFAULT_PVP_CONFIG,DEFAULT_COOP_CONFIG);assert.equal(room.fruits.length,0);advanceCoopMatch(room,.2,5001,DEFAULT_PVP_CONFIG,DEFAULT_COOP_CONFIG);assert.equal(room.status,'playing');assert.equal(room.fruits[0]!.boss,true);assert.equal(room.remainingSpawns,0);assert.ok(room.fruits[0]!.hp>DEFAULT_PVP_CONFIG.attacks.armored!.health);});
test('wall leaks end match; disconnect grace ends abandoned matches; no unearned rewards',()=>{const room=match();room.status='playing';room.wallHealth=1;room.remainingSpawns=1;room.spawnAt=10000;room.fruits=[{id:'leak',type:'normal',x:5,y:14,hp:50,boss:false}];advanceCoopMatch(room,.2,2000,DEFAULT_PVP_CONFIG,DEFAULT_COOP_CONFIG);assert.equal(room.status,'complete');assert.deepEqual(coopRewards(room,DEFAULT_COOP_CONFIG),{coins:0,gems:0,xp:0,towerXp:0});const abandoned=match();advanceCoopMatch(abandoned,.2,47000,DEFAULT_PVP_CONFIG,DEFAULT_COOP_CONFIG);assert.equal(abandoned.reason,'disconnect');});

test('equipped hero power damages the authoritative Co-op field and enforces cooldowns',()=>{const room=match();room.status='playing';room.fruits=[{id:'fruit',type:'normal',x:5,y:5,hp:100,boss:false}];const one=room.players[0]!;one.abilityLoadout=['jiju-1'];one.abilityRanks={'jiju-1':1};applyCoopCommand(room,'one',1,{type:'ability',abilityId:'jiju-1'},2000,DEFAULT_PVP_CONFIG);assert.equal(room.fruits[0]!.hp,82);assert.throws(()=>applyCoopCommand(room,'one',2,{type:'ability',abilityId:'jiju-1'},2500,DEFAULT_PVP_CONFIG),/cooling down/);});
