import { getScoreMultiplier, getStartLivesScale, getStartMoneyScale, getSuperChargeMultiplier } from '../services/liveConfig';
import { heroXpForLevel, heroXpToLevel, MAX_HERO_LEVEL, type HeroId } from './heroes';
import { modeRules } from './modes';
import { MAX_LIVES } from './world';
import { getTowerXpState, grantTowerXp } from './towerProgression';
import { getTowerMilestoneBonuses } from './towerMilestones';
export interface GameState { score:number;currency:number;lives:number;maxLives:number;wave:number;level:number;wavesInLevel:number;elapsed:number;towerLevel:number;towerXp:number;towerXpToNext:number|null;towerXpProgress:number;running:boolean;toast:string;toastTimer:number;waveSpawning:boolean;waveClearTimer:number;waveTotal:number;waveKilled:number;bossIntro:boolean;bossIntroTimer:number;hero:HeroId;heroLevel:number;heroXp:number;combo:number;comboTimer:number;superJuice:number;mode:'casual'|'ranked'|'coop'|'arena'; }
const MAX_HERO_XP=heroXpForLevel(MAX_HERO_LEVEL);
export function createState():GameState{const tower=getTowerXpState();const base:GameState={score:0,currency:140,lives:MAX_LIVES,maxLives:MAX_LIVES,wave:1,level:1,wavesInLevel:5,elapsed:0,towerLevel:1,towerXp:tower.xp,towerXpToNext:tower.nextLevelXp,towerXpProgress:tower.progress,running:true,toast:'',toastTimer:0,waveSpawning:false,waveClearTimer:2.5,waveTotal:0,waveKilled:0,bossIntro:false,bossIntroTimer:0,hero:'jiju',heroLevel:1,heroXp:0,combo:0,comboTimer:0,superJuice:0,mode:'casual'};const state=new Proxy(base,{get(target,property,receiver){if(property==='heroLevel')return heroXpToLevel(target.heroXp);if(property==='heroXp')return Math.min(MAX_HERO_XP,Math.max(0,Number(target.heroXp)||0));return Reflect.get(target,property,receiver);},set(target,property,value,receiver){if(property==='heroLevel'){target.heroLevel=Math.max(1,Math.min(MAX_HERO_LEVEL,Number(value)||1));return true;}if(property==='heroXp'){target.heroXp=Math.max(0,Math.min(MAX_HERO_XP,Number(value)||0));return true;}if(property==='lives'){const previous=Number(target.lives)||0;const next=Math.max(0,Math.min(Math.max(1,Number(target.maxLives)||MAX_LIVES),Number(value)||0));if(next<previous){target.combo=0;target.comboTimer=0;}target.lives=next;return true;}if(property==='combo'){target.combo=Math.max(0,Math.floor(Number(value)||0));return true;}return Reflect.set(target,property,value,receiver);}});if(typeof window!=='undefined')(window as Window&{__fruitTdState?:GameState}).__fruitTdState=state;return state;}
export function resetState(state:GameState):void{const hero=state.hero,heroXp=state.heroXp,tower=getTowerXpState(),mode=state.mode;Object.assign(state,createState());state.hero=hero;state.heroXp=heroXp;state.towerLevel=1;state.towerXp=tower.xp;state.towerXpToNext=tower.nextLevelXp;state.towerXpProgress=tower.progress;state.mode=mode;const rules=modeRules(mode);const bonuses=getTowerMilestoneBonuses(tower.level);state.lives=Math.max(1,Math.round((rules.lives+bonuses.startingLives)*getStartLivesScale()));state.maxLives=Math.max(state.lives,state.lives+bonuses.maxLives);state.currency=Math.max(0,Math.round(rules.startMoney*getStartMoneyScale()));}
export function leakCost(state:GameState,fruitKind:string,boss:boolean):number{const rules=modeRules(state.mode);let n=fruitKind==='bomb'?2:1;if(boss)n+=2;return Math.max(1,Math.round(n*rules.leakMul));}
export function damageTower(state:GameState,amount:number):number{const damage=Math.max(0,Math.round(amount));if(damage<=0||state.lives<=0)return 0;const actual=Math.min(state.lives,damage);state.lives-=actual;resetCombo(state,'tower_damage');return actual;}
function resetCombo(state:GameState,_reason?:string):void{state.combo=0;state.comboTimer=0;}
export function awardPerfectWave(state:GameState):number{if(state.waveKilled<=0||state.waveTotal<=0||state.waveKilled<state.waveTotal)return 0;const tower=getTowerXpState();const bonuses=getTowerMilestoneBonuses(tower.level);const reward=Math.max(4,Math.round((3+state.wave*.75)*bonuses.perfectWaveXpMultiplier));state.currency+=reward;const towerState=grantTowerXp(reward);state.towerXp=towerState.xp;state.towerXpToNext=towerState.nextLevelXp;state.towerXpProgress=towerState.progress;return reward;}
export function addScore(state:GameState,base:number):void{const rules=modeRules(state.mode),scoreMul=getScoreMultiplier(),tower=getTowerXpState(),bonuses=getTowerMilestoneBonuses(tower.level),comboMul=1+Math.min(2.5,Math.max(0,state.combo)*.08*bonuses.comboRewardMultiplier),rewarded=Math.max(0,Math.round(base*comboMul));state.score+=Math.round(rewarded*scoreMul);state.currency+=Math.max(2,Math.round(rewarded*.6*rules.currencyMul));const towerState=grantTowerXp(Math.max(1,Math.round(rewarded/6)));state.towerXp=towerState.xp;state.towerXpToNext=towerState.nextLevelXp;state.towerXpProgress=towerState.progress;}
export function chargeSuper(state:GameState,amount:number):void{state.superJuice=Math.min(100,state.superJuice+amount*getSuperChargeMultiplier());}
export function toast(state:GameState,message:string,seconds=1.8):void{state.toast=message;state.toastTimer=seconds;}
if(typeof window!=='undefined'){window.addEventListener('fruit-td-miss',()=>{const s=(window as Window&{__fruitTdState?:GameState}).__fruitTdState;if(s)resetCombo(s,'miss');});window.addEventListener('fruit-td-bomb-hit',()=>{const s=(window as Window&{__fruitTdState?:GameState}).__fruitTdState;if(s)resetCombo(s,'bomb');});}
